apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: deliverypizza
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: app-order:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
