apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: deliverypizza
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: app-auth:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
