apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: deliverypizza
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - name: catalog
        image: app-catalog:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
