name: CI/CD

on:
  push:
    branches:
      - main

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  backend:
    name: Backend lint + tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        working-directory: ./DeliveryPizza-backend
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest black ruff

      - name: Lint (black + ruff)
        working-directory: ./DeliveryPizza-backend
        run: |
          black --check .
          ruff check .

      - name: Run tests
        working-directory: ./DeliveryPizza-backend
        run: pytest


  deploy:
    name: Deploy to k3s + ngrok
    runs-on: self-hosted
    needs: backend

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f app/k8s/

      - name: Restart services
        run: |
          kubectl rollout restart deployment auth -n deliverypizza || true
          kubectl rollout restart deployment catalog -n deliverypizza || true
          kubectl rollout restart deployment order -n deliverypizza || true
          kubectl rollout restart deployment gateway -n deliverypizza || true
          kubectl rollout restart deployment frontend -n deliverypizza || true

      - name: Wait rollout
        run: |
          kubectl rollout status deployment/frontend -n deliverypizza


  ngrok:
    name: Start ngrok tunnel
    runs-on: self-hosted
    needs: deploy

    steps:
      - name: Start ngrok (frontend NodePort)
        env:
          NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
        run: |
          nohup ngrok config add-authtoken $NGROK_AUTHTOKEN
          nohup ngrok http 31405 > ngrok.log 2>&1 &

          sleep 5

      - name: Show public URL
        run: |
          URL=$(curl -s http://127.0.0.1:4040/api/tunnels \
            | jq -r '.tunnels[0].public_url')

          echo "======================================"
          echo "APP URL: $URL"
          echo "======================================"