name: CI/CD

on:
  push:
    branches:
      - main

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  backend:
    name: Backend lint + tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        working-directory: ./DeliveryPizza-backend
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest black ruff

      - name: Lint (black + ruff)
        working-directory: ./DeliveryPizza-backend
        run: |
          black --check .
          ruff check .

      - name: Run tests
        working-directory: ./DeliveryPizza-backend
        run: pytest

  deploy:
    name: Deploy
    runs-on: self-hosted

    needs: backend

    steps:
      - name: Deploy app
        run: |
          APP_DIR="/home/v1po/app"
          REPO_URL="https://github.com/v1po/DeliveryPizza.git"

          if [ ! -d "$APP_DIR/.git" ]; then
            echo "Project not found. Cloning repository..."

            git clone "$REPO_URL" "$APP_DIR"

          else
            echo "Project exists. Updating..."

            cd "$APP_DIR"

            git reset --hard
            git clean -fd

            git pull origin main

            echo "Stopping old containers..."
            docker compose down
          fi

          echo "Starting application..."

          cd "$APP_DIR"

          docker compose up -d --build

      - name: Install ngrok
        run: |
          if ! command -v ngrok &> /dev/null; then
            curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc \
              | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null

            echo "deb https://ngrok-agent.s3.amazonaws.com buster main" \
              | sudo tee /etc/apt/sources.list.d/ngrok.list

            sudo apt update
            sudo apt install ngrok -y
          fi

      - name: Configure ngrok
        run: |
          ngrok config add-authtoken ${{ secrets.NGROK_AUTHTOKEN }}

      - name: Kill old ngrok
        run: |
          pkill ngrok || true

      - name: Start ngrok
        run: |
          nohup ngrok http 80 > /tmp/ngrok.log 2>&1 &

      - name: Wait ngrok
        run: sleep 5

      - name: Show public URL
        run: |
          URL=$(curl -s http://127.0.0.1:4040/api/tunnels \
            | jq -r '.tunnels[0].public_url')

          echo ""
          echo "======================================"
          echo "APP URL: $URL"
          echo "======================================"